dist: trusty
language: node_js
node_js:
    - '8'
addons:
    firefox: latest
    chrome: stable
cache:
    directories:
        - node_modules
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
- "sudo chown root /opt/google/chrome/chrome-sandbox"
- "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
after_script: greenkeeper-lockfile-upload
install:
    - npm install
script:
    - npm test
    - npm run coverage
