dist: trusty
language: node_js
node_js:
- '8'
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- sudo chown root /opt/google/chrome/chrome-sandbox
- sudo chmod 4755 /opt/google/chrome/chrome-sandbox
- tar -tf $(npm pack)
after_script: greenkeeper-lockfile-upload
install:
- npm install
script:
- npm test
- npm run build
- npm run coverage
deploy:
  provider: npm
  email: webapps.ops@ni.com
  api_key:
    secure: AzcNj0boJWBU73bigBM9TNlo+0sp3lqDmxhxKw+GBbBAt0uelwf+GuZYG7F9OwUSBMnm5426bC1wKEkgK8mqiKEKyGsea8t5jjk7nzjVyTDDeICE2lwOqiofLa6Ei6z6iN32JSLNytkHreEDRryuVBAag0UMh1lPw+m3WmGfsbUS0OknPDafngUNCziBJK4Eejf+fAXeV6rx0TBupGOqmTj4ZqzGcJFtx47fl0fN9b+3sHjB00kb0xclNdIJEJabR3eLjkEnCmSxB+pFRVr0h/uJy1wczZh2bJ25vBHFHoGABcB3ylXp723jhH5/BptT0qXeLi5+dAaNC47v9iNwAGmfyIGQnmY2VedS6Bgr3DQ8hBImgL2G4A1DduJRGQN1wlXgv6FBnK2UvnLwFgYYa9Jlm7mh3qD5qvvvvszvBeSo9kGsttfyL9hROybk1ixJDdT62J0enNUw6hIY0KtcQ0vFrc3LC0GIMKv6YAdJs3NKg5Y//8cZq/1zZnwoxQGo45Hyc7tmKR7HKfE67XlMqlCsEAo/byDPcrEt85W8x1rMdcJIXu/8l5mRkKokaENbYdA2cDuAR1QeGdeNEVuu3Yyhf4s8q6ZjDB45wUI00hTo5YurkIJnRptvTfw/8MW6dULyWvPGUZNAmq9+fVMnCRc8qjYPOI3FSdTkNGr+9uE=
  on:
    tags: true
    repo: ni-kismet/engineering-flot
  skip_cleanup: true
env:
  secure: mkyiKGXQ8wkx4kSi/x7kProXE76E2Ix5xP+xHAcTpMhsFJYsyFE8LR8wC7UWxg80nbww6P1mWpJkMPm2QnWW8OSuKh9pF2bluTU7VAf68JHROA55FZauO0NgLWxF1tog/RLaTXBzoqXBx5+Zlcp2jl4UdsDSIr/1TogSEC7hV3dMiqzTsiC09RnAgtGsUfzDjCGVgyz2yDBMCoi+kfzJiRz7f1dW5GxhUypuV4jjEXTt1V6XrIA0C/uD27LP+kswHadMT6HURPiWEJteKNFz6hnfXttF1XmTwW++kzahDoap607oLszz+g8ss/9F0ILyO3tffyKnoEOImJLogvLUm3slxfHvh9PYh7x8oyPHFtfs7QAJ5Q2Cr23VvwJNslkuNCphEsQJS/HQ70VuSF6MlGrhbsLGp8kEFZrXADqojkGQ/duPk3QykiXUaUxr0uPEllptOLh5TTKYarRM/IVv4kE5iC4egJXouKxwwL5LIglnyCTycEdTLv/IUfYap8ABqi20eBm+AJGk44Z72fl+G/xoPrzbtVosQfPbuLurVJHHDDExHM3bFqfUNnB9xIEwWTihSc6ycI7IhuMQlg1G1t5rRY5YyVQN/4oP4k6qNgYbJs9PrxfyMw7Z+dSg/L2SyJbc/ReNiFkvpTNDYGY/dULvx1uGM1NGdmC+z+nljfk=
