dist: trusty
language: node_js
node_js:
- '6'
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
    - npm install travis-github-lint-status eslint-config-standard eslint-plugin-standard eslint-plugin-promise
script:
    - ./node_modules/travis-github-lint-status/index.js
    - npm test
    - npm run coverage
after_success:
    - ./node_modules/.bin/codecov
