dist: trusty
language: node_js
node_js:
- '6'
addons:
  firefox: latest
  chrome: stable
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
install:
    - npm install
    #- npm install travis-github-lint-status eslint-config-standard eslint-plugin-standard eslint-plugin-promise
script:
    - npm test
    - npm run coverage
    #- ./node_modules/travis-github-lint-status/index.js ./*.js
